server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: reserve
          uri: http://localhost:8081
          predicates:
            - Path=/reservations/**, 
        - id: room
          uri: http://localhost:8082
          predicates:
            - Path=/rooms/**, 
        - id: notify
          uri: http://localhost:8083
          predicates:
            - Path=/notifications/**, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: reserve
          uri: http://reserve:8080
          predicates:
            - Path=/reservations/**, 
        - id: room
          uri: http://room:8080
          predicates:
            - Path=/rooms/**, 
        - id: notify
          uri: http://notify:8080
          predicates:
            - Path=/notifications/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
